name: HealthCheck

on: push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Running docker-compose
        env:

          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_HOST: ${{ secrets.DB_HOST }}
          ENV: ${{ secrets.ENV }}

        run: docker-compose up --exit-code-from tests || true

      - name: Copy gh-pages history
        run: |
          sudo mkdir -p allure-results/history
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/

      - name: Generate Allure report
        run: docker-compose run tests /bin/sh -c "allure generate allure-results --clean -o allure-reports"

      - name: Copy to gh-pages
        run: |
          sudo cp -R allure-results/history/* ./.github/gh-pages/history
          

      - name: Deploy Allure report
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-reports


